### ISSUE TITLE
unable to install and use

### ISSUE THREAD

**Issue by Akshay-Arjun** [raverrr/plution#2]
`go install github.com/raverrr/plution@latest`  used go install since go get is not working anymore.

 results : 

```
go: downloading github.com/raverrr/plution v0.0.0-20210801124607-0a45d4e24ae4
go: finding module for package github.com/fatih/color
go: finding module for package github.com/chromedp/chromedp
go: downloading github.com/chromedp/chromedp v0.7.8
go: downloading github.com/fatih/color v1.13.0
go: found github.com/chromedp/chromedp in github.com/chromedp/chromedp v0.7.8
go: found github.com/fatih/color in github.com/fatih/color v1.13.0
go: downloading github.com/mattn/go-colorable v0.1.9
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/chromedp/cdproto v0.0.0-20220217222649-d8c14a5c6edf
go: downloading github.com/gobwas/ws v1.1.0
go: downloading golang.org/x/sys v0.0.0-20220209214540-3681064d5158
```
`$ cat URLs.txt | plution `                    
cat: URLs.txt: No such file or directory
plution: command not found

**Comment by raverrr** [comment]
Hi.
Looks like you don't have go in your path.

Plution installs and works fine for me :)

David

**Comment by Akshay-Arjun** [comment]
**Can you help me on how to add Go to my path? I installed it using their installation setup and tried to install plution .** I'm very new to GO couldn't understand how it actually works.

**Comment by raverrr** [comment]
Sure
Can you help me write a training and development proposal for my board of
directors in return? I'm quite new to writing proposals
